export interface ServiceItem {
  id: string;
  name: string;
  description: string;
  price: string;
  duration: string;
  icon: string;
  category: string;
}

export const services: ServiceItem[] = [
  // Hair Services
  {
    id: "haircut",
    name: "Haircut",
    description: "Classic or modern haircut tailored to your style and face shape.",
    price: "AED 15",
    duration: "30 min",
    icon: "scissors",
    category: "Hair",
  },
  {
    id: "hair-styling",
    name: "Hair Styling",
    description: "Professional styling with premium products for any occasion.",
    price: "AED 10",
    duration: "25 min",
    icon: "sparkles",
    category: "Hair",
  },
  {
    id: "hair-colour",
    name: "Hair Colour",
    description: "Full hair colouring with premium dyes for a bold new look.",
    price: "AED 30",
    duration: "60 min",
    icon: "palette",
    category: "Hair",
  },
  {
    id: "hair-wash",
    name: "Hair Wash",
    description: "Relaxing hair wash with premium shampoo and conditioner.",
    price: "AED 10",
    duration: "15 min",
    icon: "droplets",
    category: "Hair",
  },
  {
    id: "hair-straightening",
    name: "Hair Straightening",
    description: "Professional hair straightening for a sleek, smooth finish.",
    price: "AED 40",
    duration: "20 min",
    icon: "align-horizontal-justify-center",
    category: "Hair",
  },
  {
    id: "Shaded Color",
    name: "Shaded Color",
    description: "Professional Shaded Color.",
    price: "AED 150",
    duration: "60 min",
    icon: "yup",
    category: "Hair",
  },{
    id: "keratin",
    name: "Keratin Treatment",
    description: "Depends on Hsir Lenght.",
    price: "AED 150/200",
    duration: "60 min",
    icon: "flask-conical",
    category: "Hair",
  },
  {
    id: "prum",
    name: "Prum",
    description: "Depends on Hsir Lenght.",
    price: "AED 100/200",
    duration: "90 min",
    icon: "waves",
    category: "Hair",
  },
  {
    id: "highlights",
    name: "Highlights",
    description: "Precision highlights to add dimension and style to your hair.",
    price: "AED 150",
    duration: "75 min",
    icon: "sun",
    category: "Hair",
  },
  {
    id: "anti-dandruff",
    name: "Anti Dandruff Treatment",
    description: "Specialized treatment to eliminate dandruff and soothe the scalp.",
    price: "AED 40",
    duration: "45 min",
    icon: "shield-check",
    category: "Hair",
  },
  // Beard & Shaving
  {
    id: "beard-trim",
    name: "Beard Trimming",
    description: "Precision beard trimming and shaping for a clean, sharp look.",
    price: "AED 15",
    duration: "15 min",
    icon: "ruler",
    category: "Beard & Shave",
  },
  {
    id: "shaving",
    name: "Shaving",
    description: "Hot towel straight razor shave for the ultimate smooth finish.",
    price: "AED 15",
    duration: "25 min",
    icon: "minus",
    category: "Beard & Shave",
  },
  {
    id: "beard-colour",
    name: "Beard Colour",
    description: "Professional beard colouring for a fresh, polished appearance.",
    price: "AED 30",
    duration: "30 min",
    icon: "paintbrush",
    category: "Beard & Shave",
  },
  // Skin & Face
  {
    id: "facials",
    name: "Facials",
    description: "Rejuvenating facial treatment for clean, glowing skin.",
    price: "AED 80",
    duration: "45 min",
    icon: "sparkles",
    category: "Skin & Face",
  },
  {
    id: "face-cleansing",
    name: "Face Cleansing",
    description: "Deep face cleansing to remove impurities and refresh your skin.",
    price: "AED 50",
    duration: "30 min",
    icon: "droplets",
    category: "Skin & Face",
  },
  {
    id: "face-waxing",
    name: "Face Waxing",
    description: "Gentle facial waxing for smooth, hair-free skin.",
    price: "AED 20",
    duration: "20 min",
    icon: "user",
    category: "Waxing",
  },
  // Waxing
  
  {
    id: "underarm-waxing",
    name: "UnderArm Waxing",
    description: "Quick and effective underarm waxing for lasting smoothness.",
    price: "AED 40",
    duration: "20 min",
    icon: "user",
    category: "Waxing",
  },
  {
    id: "full-body-waxing",
    name: "Full Body Waxing",
    description: "Complete full body waxing for ultimate smoothness and comfort.",
    price: "AED 100/150/200",
    duration: "90 min",
    icon: "user",
    category: "Waxing",
  },
  // Grooming & Spa
  {
    id: "manicure",
    name: "Manicure",
    description: "Professional manicure for well-groomed, clean nails.",
    price: "AED 40",
    duration: "30 min",
    icon: "hand",
    category: "Grooming & Spa",
  },
  {
    id: "pedicure",
    name: "Pedicure",
    description: "Relaxing pedicure treatment for smooth, refreshed feet.",
    price: "AED 40",
    duration: "40 min",
    icon: "footprints",
    category: "Grooming & Spa",
  },
  {
    id: "foot-spa",
    name: "Foot Spa",
    description: "Luxurious foot spa to relax tired feet and rejuvenate.",
    price: "AED 40",
    duration: "45 min",
    icon: "bath",
    category: "Grooming & Spa",
  },
  {
    id: "head-massage",
    name: "Head Massage",
    description: "Soothing head massage to relieve stress and tension.",
    price: "AED 20",
    duration: "15 min",
    icon: "brain",
    category: "Grooming & Spa",
  },
  {
    id: "full-body-massage",
    name: "Full Body Massage",
    description: "Complete relaxation with a professional full body massage.",
    price: "AED 60/150",
    duration: "30 min 1 hour",
    icon: "heart-pulse",
    category: "Grooming & Spa",
  },
  // Therapy
  {
    id: "hijama",
    name: "Hijama (Cupping Therapy)",
    description: "Traditional cupping therapy for detox and pain relief.",
    price: "AED 100",
    duration: "45 min",
    icon: "circle-dot",
    category: "Therapy",
  },
];

export const serviceCategories = [...new Set(services.map((s) => s.category))];
